import "../../../assets/styles/globals.css";

import { Metadata } from "next";
import { getServerSession, Session } from "next-auth";
import React, { JSX } from "react";

import { Providers } from "@/app/providers";
import { authOptions } from "@/lib/auth";

let session: Session | null;

export const metadata: Metadata = {
  title: "EP",
  description: "Generated by create next (app)",
};

async function userConnected(): Promise<boolean> {
  session = await getServerSession(authOptions);
  return session !== null;
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <Providers>
      <main className="flex-grow mx-auto">
        <div className="w-full">{children}</div>
      </main>
    </Providers>
  );
}
